---
locale: es
tags: []
layout: input_bottom
editor: code
type: problem
extra_visible: false
teacher_info: Arreglado por Estefanía Miguel y sus estudiantes del 1er cuatrimestre
  2021 de la UNDAV
manual_evaluation: false
choices: []
name: Mensajeria recargada
